version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

  tacos-deploy:
    docker:
      - image: circleci/python:2.7-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

workflows:
  version: 2
  dev-deployment:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - tacos-hold:
          type: approval
          requires:
           - build
      - brisket-hold:
          type: approval
          requires:
           - build
      - triangle-hold:
          type: approval
          requires:
           - build
      - tacos-deploy:
          requires:
            - tacos-hold
      - triangle-deploy:
          requires:
            - triangle-hold
      - brisket-deploy:
          requires:
            - brisket-hold
